version: "3.3"
services:
  vote:
    build: ./vote
    depends_on:
      - redis
    ports: 
      - "80:80"
  redis:
    image: redis
    restart: always
    depends_on:
      - worker
  worker:
    build: ./worker
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    depends_on:
      - result
  result:
    build: ./result
    ports:
      - "81:80"

